import{a as m,S as L,i as M}from"./assets/vendor-2618a76b.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const t={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),searchBtn:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),loader:document.querySelector(".loader")};m.defaults.baseURL="https://pixabay.com/api";const v="41899926-74a7536d4d492e936dbb67b5b",n="is-hidden";let c=1,d="",y=0;t.form.addEventListener("submit",q);async function q(r){if(r.preventDefault(),t.gallery.innerHTML="",c=1,t.loadMoreBtn.classList.add(n),d=t.form.query.value.trim(),!d){u("The search field can't be empty! Please, enter your request!");return}try{const{hits:s,total:a}=await p(d);y=Math.ceil(a/40),g(s,t.gallery),s.length>0?(t.loadMoreBtn.classList.remove(n),t.loadMoreBtn.addEventListener("click",S)):(t.loadMoreBtn.classList.add(n),u("Sorry, there are no images matching your search query. Please, try again!")),f(!1)}catch(s){console.log(s)}finally{t.form.reset(),c===y&&(t.loadMoreBtn.classList.add(n),u("We're sorry, but you've reached the end of search results!"))}}async function S(){c+=1;try{f(!0),t.loadMoreBtn.classList.add(n);const{hits:r}=await p(d,c);g(r,t.gallery),f(!1),B(),t.loadMoreBtn.classList.remove(n)}catch(r){console.log(r)}finally{c>y&&(t.loadMoreBtn.classList.add(n),u("We're sorry, but you've reached the end of search results!"))}}async function p(r,s=1){return f(!0),m.get("/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:s}}).then(({data:a})=>a)}function g(r){const s=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:l,comments:h,downloads:b})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${a}"
      alt="${e}"
    />
    <p class="gallery-descr">likes: <span class="descr-span">${o}</span> views: <span class="descr-span">${l}</span> comments: <span class="descr-span">${h}</span> downloads: <span class="descr-span">${b}</span></p>
  </a>
</li>`).join("");t.gallery.insertAdjacentHTML("beforeend",s),new L(".gallery-item a",{captionsData:"alt",captionDelay:250})}function u(r){M.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function f(r=!0){t.loader.style.display=r?"inline-block":"none"}function B(){const r=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
